// Netlify Function: Generate product mockup from Printful
// TODO: Import generateMockup when API key is configured

exports.handler = async (event, context) => {
  const headers = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Content-Type': 'application/json'
  }

  if (event.httpMethod === 'OPTIONS') {
    return { statusCode: 200, headers, body: '' }
  }

  if (event.httpMethod !== 'POST') {
    return {
      statusCode: 405,
      headers,
      body: JSON.stringify({ error: 'Method not allowed' })
    }
  }

  try {
    const { productId, variantId, phrase, placement, textOnly, color, size } = JSON.parse(event.body)

    if (!productId || !variantId || !phrase) {
      return {
        statusCode: 400,
        headers,
        body: JSON.stringify({ error: 'Missing required parameters: productId, variantId, phrase' })
      }
    }

    if (!process.env.PRINTFUL_API_KEY) {
      return {
        statusCode: 200,
        headers,
        body: JSON.stringify({
          mockupUrl: null,
          message: 'Printful API not configured. Add PRINTFUL_API_KEY to Netlify environment variables.',
          placeholder: true
        })
      }
    }

    // TODO: When API key is configured, generate actual mockup with text-only design
    // For now, return a placeholder that indicates text-only design
    // The actual mockup will be generated by Printful API with:
    // - Text-only design (no logo/branding)
    // - Selected phrase as text
    // - Proper placement and sizing
    
    // Placeholder: In production, this will call Printful API to generate mockup
    // with the phrase as text-only design
    const mockupUrl = null

    return {
      statusCode: 200,
      headers,
      body: JSON.stringify({ mockupUrl })
    }
  } catch (error) {
    console.error('Error generating mockup:', error)
    return {
      statusCode: 500,
      headers,
      body: JSON.stringify({ error: 'Failed to generate mockup' })
    }
  }
}
